/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        border: 'var(--color-border)',
        gold: 'var(--color-gold)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-dim': 'var(--color-text-dim)',
        verified: 'var(--color-verified)',
        warn: 'var(--color-warn)',
        danger: 'var(--color-danger)',
        info: 'var(--color-info)',
        conflict: 'var(--color-conflict)',
        narrative: 'var(--color-narrative)',
        'card-bg': 'var(--color-card-bg)',
        'card-border': 'var(--color-card-border)',
        'card-hover': 'var(--color-card-hover)',
        'gold-bg': 'var(--color-gold-bg)',
        'green-bg': 'var(--color-green-bg)',
        'red-bg': 'var(--color-red-bg)',
        'indigo-bg': 'var(--color-indigo-bg)',
        indigo: 'var(--color-indigo)',
      },
      fontFamily: {
        sans: ['DM Sans', 'sans-serif'],
        display: ['Cormorant Garamond', 'serif'],
        data: ['IBM Plex Mono', 'monospace'],
        mono: ['IBM Plex Mono', 'monospace'],
      },
      fontSize: {
        heading: '22px',
        subheading: '16px',
        body: '14px',
        label: '11px',
        micro: '9px',
      },
    },
  },
  plugins: [],
};
